# Generated by Django 2.0.7 on 2018-07-09 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('googlecalendar', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calendar',
            old_name='name',
            new_name='location',
        ),
    ]
